Repository go-vela/vela-k6, pull requests merged in 2023-08, with the labels that each got.

#6 feat: add workflows
  .github/README.md
  .github/workflows/build.yml
  .github/workflows/labeler.yml
  .github/workflows/prerelease.yml
  .github/workflows/publish.yml
  .github/workflows/reviewdog.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
  .gitignore
  .golangci.yml
  Dockerfile
  Makefile
  go.mod
  go.sum
  main.go
  plugin/mock.go
  plugin/plugin.go
  plugin/plugin_test.go
  version/version.go
Labels: size/l

#13 feat: adding code coverage
  go.sum
  version/version.go
  version/version_test.go
Labels: size/m

#16 feat: setup script
  .gitignore
  DOCS.md
  Dockerfile
  Makefile
  main.go
  plugin/mock.go
  plugin/plugin.go
  plugin/plugin_test.go
Labels: size/l

#17 chore: markdown lint
  .github/CODEOWNERS
  .github/CONTRIBUTING.md
  .github/README.md
  .github/workflows/reviewdog.yml
  DOCS.md
  Makefile
Labels: size/s

#18 chore: yaml lint
  .github/workflows/build.yml
  .github/workflows/labeler.yml
  .github/workflows/prerelease.yml
  .github/workflows/publish.yml
  .github/workflows/reviewdog.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
  .golangci.yml
  .yamllint.yml
  Makefile
Labels: size/xl

#20 chore: add codecov.yml
  codecov.yml
Labels: size/s

#21 chore: restructure
  Makefile
  cmd/vela-k6/main.go
  plugin/mock.go
  plugin/mock/plugin.go
  plugin/plugin.go
  plugin/plugin_test.go
  types/types.go
Labels: size/m

#22 chore: fix docs description header
  DOCS.md
  Makefile
Labels: size/s
